import { CATALOG, ORGANISMS, MUTATIONS, RESOURCE_KEYS, SYSTEM_NAMES } from './content.js';
import { getCaps, getRoutes, getEncounter, getItemStats, classifyBuild, scoreRun, neighbours, getPlan, createRun, act, simulate, getLifeSupport, getPeopleRecord } from './engine.js';
import { icon, esc, signed } from './icons.js';
import { roomArt } from './art.js';
import { getVisualLinks, ecologyOverlay, ecologyNote } from './ecology.js';
import { seedChooser, bankingPanel, genomeBank, blueprintGallery } from './lineage-views.js';
import { mutationComparison, offerForRoute, rateText, reportSummary, plannedRepairEvent } from './guidance.js';
import { crossingNotice, flightPlan, portExchangeMarkup, trendMarkup } from './crossing-views.js';
import { peopleDemand, rescueOffer, rescueForecastNote, rescueEncounter, peopleEnding } from './rescue-views.js';
import { finalDepartureOffer, selectedRouteForecast, finalDepartureControls } from './departure-views.js';

const labels = {power:'Power', oxygen:'Oxygen', biomass:'Food', heat:'Heat', hull:'Hull'};
const allResources = ['power','oxygen','biomass','heat','hull'];
const typeNames = {garden:'GARDEN SIGNAL',salvage:'DERELICT SIGNAL',anomaly:'ANOMALOUS SIGNAL'};
export const nameOf = id => CATALOG[id]?.name || id;
const button = (action,label,options='') => `<button type="button" data-action="${action}" ${options}>${label}</button>`;
export function flows(specimen,state=null,forecast=null) {
  if(['engine','crew'].includes(specimen.id)){const life=getLifeSupport(state);return `<div class="flows"><span class="flow muted">Jump demand: 4 power · ${life.oxygen} oxygen · ${life.biomass} food</span></div>`;}
  if(specimen.id==='storage')return '<div class="flows"><span class="flow muted">Adds 10 capacity each: power, oxygen and food.</span></div>';
  const index=state?.grid.findIndex(x=>x?.uid===specimen.uid) ?? -1;
  const grid=forecast?.grid || state?.grid || [];
  const symbioticActive=index>=0&&neighbours(index).some(i=>grid[i]?.active&&grid[i]?.id!==specimen.id&&CATALOG[grid[i]?.id]?.kind==='organism');
  const report=forecast?.cellReports?.[index];
  const cell=report?.uid===specimen.uid?report:null,dormant=cell?.status==='dormant';
  const stats = cell&&!dormant?{input:cell.inputs,output:cell.outputs,defence:cell.defence}:getItemStats(specimen,{ruleset:state?.ruleset,hazard:forecast?.route?.hazard||state?.route?.hazard,symbioticActive});
  const inputs = Object.entries(stats.input || {}).filter(([,n])=>n).map(([r,n])=>`<span class="flow cost ${r}" tabindex="0" role="button" data-help="${r}" aria-label="${n} ${labels[r]||r} input; explain ${labels[r]||r}">${icon(r)}${n}<span class="sr-only"> ${labels[r]||r} input</span></span>`).join('');
  const outputs = Object.entries(stats.output || {}).filter(([,n])=>n).map(([r,n])=>`<span class="flow ${r}" tabindex="0" role="button" data-help="${r}" aria-label="${signed(n)} ${labels[r]||r} output; explain ${labels[r]||r}">${icon(r)}${signed(n)}<span class="sr-only"> ${labels[r]||r} output</span></span>`).join('');
  const flow=`<div class="flows" aria-label="${dormant?'Conditional':'Per jump'} inputs and outputs">${dormant?'<span class="flow-condition">If active</span>':''}${inputs || '<span class="flow muted">No input</span>'}<span class="flow-arrow">→</span>${outputs}${stats.defence ? `<span class="flow hull">${icon('hull')}blocks ${stats.defence}</span>` : !outputs?'<span class="flow muted">No production</span>':''}</div>`;
  return dormant?`<div class="dormant-flow">${flow}<p class="flow-idle-result">This jump: no consumption or output.</p></div>`:flow;
}

function starvationTiming(cell,forecast) {
  return cell?.status==='dormant'&&forecast?.events?.some(e=>e.type==='dormant'&&e.source===cell.uid)
    ? '<p class="operating-context">End stores include later production. This room must pay its inputs first.</p>' : '';
}
export function header(state,ui,snapshot) {
  return `<header class="topbar"><a href="#" class="brand" data-action="home" aria-label="ARKSHIP home"><img src="assets/mark.svg" alt="" width="31" height="31"><span>ARKSHIP<span class="brand-dot">.</span></span></a><span class="top-caption">A LIVING VOYAGE</span><nav aria-label="Game controls">${button('guide',icon('info'),'class="icon-button" aria-label="How to play" data-focus="guide"')}${button('sound',icon(snapshot.settings.sound?'sound':'mute'),`class="icon-button" aria-label="${snapshot.settings.sound?'Mute sound':'Enable sound'}" aria-pressed="${snapshot.settings.sound}" data-focus="sound"`)}${button('sound-settings','Mix',`class="text-button mix-toggle" aria-label="Audio settings" aria-expanded="${!!ui.soundOpen}" data-focus="sound-settings"`)}${button(ui.page==='archive'?'back':'archive',`${icon(ui.page==='archive'?'back':'archive')}<span>${ui.page==='archive'?'Back to ship':'Genome archive'}</span>`,`class="archive-button" aria-label="${ui.page==='archive'?'Back to ship':'Genome archive'}" data-focus="archive"`)}</nav>${ui.soundOpen?`<aside class="audio-settings" aria-label="Audio mix"><strong>Sound aboard</strong><p>${snapshot.settings.sound?'Audio enabled':'Master sound is muted'}</p>${button('music',`Music & ambience · ${ui.preferences.music?'on':'off'}`,`class="secondary" aria-pressed="${ui.preferences.music}" data-focus="music"`)}${button('effects',`Action effects · ${ui.preferences.effects?'on':'off'}`,`class="secondary" aria-pressed="${ui.preferences.effects}" data-focus="effects"`)}${button('sound-settings','Close','class="text-button"')}</aside>`:''}</header>`;
}
export function pressures(state,forecast=null) {
  const caps=getCaps(state);
  return `<section class="pressures" aria-label="Stored ship resources"><span class="resource-caption">STORED RESERVES</span>${allResources.map(r=>{
    const n=state.resources[r], bad=r==='heat'?n>15:n<=(r==='hull'?8:5);
    return `<button type="button" data-help="${r}" class="pressure ${r} ${bad?'critical':''}" aria-label="${labels[r]} ${n}. ${r==='heat'?'Safe through 15. ':''}Explain ${labels[r]}."><span class="pressure-name">${icon(r)}<span>${labels[r]}</span>${bad?icon('alert','tiny'):''}</span><span class="pressure-reading"><strong data-resource="${r}">${n}</strong><span>${r==='heat'?'≤15 safe':`/${caps[r]||40}`}</span></span><span class="meter"><i style="width:${Math.max(0,Math.min(100,n/(caps[r]||40)*100))}%"></i>${r==='heat'?'<i class="heat-threshold" style="left:37.5%"></i>':''}</span>${forecast?`<span class="pressure-forecast"><span>After</span><b>${forecast.resources[r]}</b></span>`:''}</button>`;
  }).join('')}</section>`;
}
export function journey(state) {
  return `<div class="journey" aria-label="System ${state.system} of 10">${Array.from({length:10},(_,i)=>`<span class="waypoint ${i+1<state.system?'visited':''} ${i+1===state.system?'current':''}">${i+1===state.system?`<b>${String(i+1).padStart(2,'0')}</b>`:i+1===10?icon('star'):''}</span>`).join('')}</div>`;
}
export function ship(state,ui,forecast,preview=false) {
  const visualLinks=getVisualLinks(forecast);
  const selected=Number.isInteger(ui.selected)?state.grid[ui.selected]:null;
  const placement = ui.placing ? state.cargo.find(x=>x.uid===ui.placing) : null;
  const isBuild=state.phase==='build'&&!preview;
  const selectedReport=forecast?.cellReports?.[ui.selected];
  const localTargets=selectedReport?.localTargets||[];
  const glow=new Set([...localTargets.map(t=>t.index),...visualLinks.filter(link=>link.kind==='symbiosis'&&(link.source===ui.selected||link.target===ui.selected)).map(link=>link.source===ui.selected?link.target:link.source)]);
  const dangerous=new Set(localTargets.filter(t=>['danger','mutation'].includes(t.kind)).map(t=>t.index));
  const open=new Set(state.openBays||Array.from({length:20},(_,i)=>i));
  const free=[...open].filter(i=>!state.grid[i]).length;
  const bio=state.grid.filter(x=>x && CATALOG[x.id]?.kind==='organism').length;
  return `<section class="ship-scene ${preview?'preview-scene':''} ${bio>4?'lush':''}" aria-label="Your ark" style="--bio:${bio}"><div class="scene-top"><div><span class="eyebrow">${preview?'THE LAST SEED OF HOME':`SYSTEM ${String(state.system).padStart(2,'0')} / 10`}</span><h1>${preview?'Life finds a way.':state.outcome==='win'?'Eos Refuge.':esc(SYSTEM_NAMES[state.system-1] || 'The Far Shore')}</h1></div><span class="crew-count">${icon('crew')}<b>${Math.max(0,state.crew)}</b><span>aboard</span></span></div>${journey(state)}${!preview?`<p class="voyage-guidance">${state.outcome?`${state.outcome==='win'?'AT EOS REFUGE':state.outcome==='evacuation'?'ARK ABANDONED':'VOYAGE LOST'} · ${state.turn} jumps crossed`:`Eos Refuge · ${Math.max(0,9-state.turn)} ${9-state.turn===1?'jump remains':'jumps remain'}`}<span>${state.outcome?'Voyage complete':state.system<4?'Service beacon at 4':state.system<7?'Evacuation beacon at 7':state.system===7?'Evacuation beacon available':'Final approach'}</span></p>`:''}
  ${!preview&&!state.outcome?peopleDemand(state,forecast):''}<div class="space-stage"><div class="orbital-ring" aria-hidden="true"></div><span class="scene-coordinate" aria-hidden="true">ARK—07<br>BOTANICAL VESSEL</span><div class="ship-body ${ui.jumping?'jumping':''}"><div class="ship-nose" aria-hidden="true"><div class="cockpit"></div><span>07</span></div><div class="nacelle nacelle-left" aria-hidden="true"></div><div class="nacelle nacelle-right" aria-hidden="true"></div><div class="hull-frame"><div class="ship-grid" role="group" aria-label="Ship bays. Use arrow keys to navigate, Enter to select.">${state.grid.map((item,i)=>{
    const data=item?CATALOG[item.id]:null;
    const sealed=!open.has(i);
    const suggested=!sealed&&isBuild&&state.turn===0&&placement?.id==='void-lung'&&[1,5,8,10].includes(i)&&neighbours(i).some(n=>state.grid[n]?.id==='hydroponics');
    return `<button type="button" class="bay ${sealed?'sealed':item?'occupied':'empty'} ${data?.kind==='organism'?'organic':''} ${ui.selected===i?'selected':''} ${glow.has(i)?'linked':''} ${dangerous.has(i)?'danger-linked':''} ${isBuild&&(ui.placing||ui.moving!==null)&&!item&&!sealed?'place-target':''} ${suggested?'suggested':''} ${item?.mutation?'mutated '+item.mutation:''} ${item?.paused?'paused':''} ${forecast?.cellReports?.[i]?.status==='dormant'?'inactive':''}" data-action="bay" data-help-bay="${i}" data-index="${i}" data-item="${item?.id||''}" data-focus="bay-${i}" tabindex="${ui.gridFocus===i?'0':'-1'}" aria-label="Row ${Math.floor(i/5)+1}, column ${i%5+1}: ${esc(sealed?'sealed bay, 4 food to reclaim':data?.name||'empty bay')}${data?.anchored?', anchored':''}${item?.mutation?', '+item.mutation+' mutation':''}" ${preview?'disabled':''}>${roomArt(item,{lazy:i>9})}${sealed?`<span class="sealed-mark">${icon('lock')}</span>`:!item?`<span class="empty-mark">${icon('plus')}</span>`:''}${item?.mutation?`<span class="mutation-mark" aria-hidden="true">${item.mutation==='feral'?'F':item.mutation==='efficient'?'E':'S'}</span>`:''}${item?.paused?'<span class="operation-mark" aria-hidden="true">Ⅱ</span>':''}${['report','ended'].includes(state.phase)&&forecast?.cellReports?.[i]?.trajectory?.grewThisJump?'<span class="growth-mark">NEW</span>':''}${item&&isBuild?`<span class="bay-number">${String(i+1).padStart(2,'0')}</span>`:''}</button>`;
  }).join('')}${ecologyOverlay(visualLinks,ui.selected)}</div></div><div class="engine-tail" aria-hidden="true"><i></i><i></i><i></i></div></div><span class="scene-scale" aria-hidden="true">${state.outcome==='loss'||state.outcome==='evacuation'?'OFFLINE':'PRESSURISED'}<br><b>20 BAYS</b></span></div>
  <div class="ship-caption ${isBuild?'building-caption':''}"><span><i class="status-light"></i>${preview?'A ship. A garden. A second chance.':esc(classifyBuild(state).name)}</span><span>${state.outcome==='win'?`${new Set(state.grid.filter(x=>x&&CATALOG[x.id]?.kind==='organism').map(x=>x.id)).size} species carried · ${state.grid.filter(x=>x?.mutation).length} evolved`:`${free} open bays free<span class="desktop-only"> · ${20-open.size} sealed</span>`}</span></div>${visualLinks.length?'<p class="ecology-legend"><span class="synergy-key">Mint · synergy</span><span class="symbiosis-key">Violet · Symbiotic support</span><span>Tap a room to trace it</span></p>':''}${ecologyNote(visualLinks,ui.selected)}${isBuild?deckToolbar(state,ui,forecast):''}</section>`;
}

function deckToolbar(state,ui,forecast) {
 const item=ui.placing?state.cargo.find(x=>x.uid===ui.placing):Number.isInteger(ui.selected)?state.grid[ui.selected]:null;
 const data=item?CATALOG[item.id]:null,moving=ui.moving!==null;
 const onShip=Boolean(item)&&Number.isInteger(ui.selected)&&state.grid[ui.selected]?.uid===item.uid;
 const plan=getPlan(state),sealed=Number.isInteger(ui.reclaimTarget)&&!state.openBays.includes(ui.reclaimTarget);
 const canReclaim=sealed&&neighbours(ui.reclaimTarget).some(i=>state.openBays.includes(i));
 const currentCell=onShip?forecast?.cellReports?.[ui.selected]:null;
 const title=sealed?'A sealed hold.':ui.placing?`Graft ${esc(data?.name)}`:moving?`Move ${esc(data?.name)}`:item?esc(data.name):'Touch a room. Shape your ark.';
 return `<div class="deck-toolbar"><div class="deck-toolbar-heading"><b>${title}</b>${item&&!sealed&&currentCell?.status!=='dormant'?flows(item,state,forecast):''}${button('show-forecast','Forecast','class="text-button forecast-link" data-focus="show-forecast"')}</div>${currentCell?.status==='dormant'?`${flows(item,state,forecast)}<p class="deck-status danger-text">${icon('alert')}${esc(currentCell.reason)}</p>${starvationTiming(currentCell,forecast)}`:''}${onShip&&state.turn===0&&item?.id==='void-lung'?`<p class="first-synergy">${neighbours(ui.selected).some(i=>state.grid[i]?.id==='hydroponics')?'Beside hydroponics: +2 food each jump.':'Beside hydroponics, this Lung gives +2 food each jump.'}</p>`:''}<div class="placement-status ${ui.placing||moving?'active':''}">${sealed?`<span>${canReclaim?'4 food on commit to open this hold.':'Open a neighbouring hold first.'}</span>${button('reclaim','Plan reclaim',`class="secondary" data-focus="reclaim" ${canReclaim?'':'disabled'}`)}`:ui.placing||moving?`<span>Tap an open, empty bay.</span>${button('show-bays','Show bays','class="text-button"')}${button('cancel','Cancel','class="secondary" data-focus="cancel"')}`:onShip&&!data.anchored?`<div class="deck-actions">${button('move',`${icon('move')} Move`,'class="secondary" data-focus="move"')}${button('store',`${icon('archive')} Store`,`class="secondary" data-focus="store" ${state.cargo.length>=8?'disabled aria-describedby="cargo-full-reason"':''}`)}${state.ruleset>=4&&item.id!=='storage'?button('operation',item.paused?'Resume operation':'Pause operation',`class="secondary operation-toggle" data-focus="operation" aria-pressed="${!item.paused}"`):''}${data.kind==='organism'&&!item.mutation?button('show-mutation',`${icon('mutation')} Mutate`,'class="secondary" data-focus="show-mutation"'):button('inspect',`${icon('info')} Details`,'class="secondary" data-focus="inspect"')}</div>`:`<span>${item?'Anchored core system.':'Choose a specimen from cargo to graft it.'}</span>`}</div>${onShip&&state.cargo.length>=8?'<p class="field-note" id="cargo-full-reason">Cargo is full. Graft or discard a stored specimen to make room.</p>':''}</div>`;
}

export function welcome(state,ui,snapshot) {
 return `<main class="welcome layout">${ship(state,{...ui,selected:null,placing:null},null,true)}<section class="decision welcome-decision" id="decision" tabindex="-1"><span class="eyebrow mint">DESTINATION / EOS REFUGE</span><h2>Carry life<br>into the unknown.</h2><p class="intro">Your ship is the ecosystem.<br>Graft strange life. Keep it alive.<br>Reach the refuge. Carry more people when your ark can support them.</p><div class="voyage-facts"><span><b>9</b> jumps</span><span><b>6</b> people at launch</span><span><b>10</b> open bays</span></div><form id="start-form"><label for="seed">Voyage code <span>Same code. Same opportunities.</span></label><input id="seed" name="seed" maxlength="40" value="${esc(ui.seed||'PALE-BLUE-7')}" autocomplete="off" spellcheck="false" required>${seedChooser(snapshot.archive,ui)}<label class="guide-choice"><input type="checkbox" name="guide" ${ui.guideChoice?'checked':''}> Guide my first two jumps</label><button class="primary launch" type="submit">Begin voyage ${icon('arrow')}</button></form><p class="save-note">${icon('check')} ${snapshot.available?'Your voyage and lineage save on this device.':'Storage unavailable. This voyage will be unsaved.'}</p><details class="launch-chart"><summary>Crossings & lifeboats · View flight plan</summary><div class="launch-plan">${flightPlan(createRun(ui.seed?.trim()||'PALE-BLUE-7',{},[],{ruleset:5}))}</div></details><p class="welcome-foot">WHAT WILL YOUR SHIP BECOME?</p></section></main>`;
}

function hazardText(route) {
  const h=typeof route.hazard==='string'?route.hazard:route.hazard?.id;
  return {solar:'Solar flare · +5 heat',debris:'Debris field · −4 hull',spores:'Spore cloud · −3 oxygen'}[h]||route.hazard?.description||'Uncharted conditions';
}
function rewardName(route) {
  if(typeof route.reward==='string') return nameOf(route.reward);
  return nameOf(route.reward?.item || route.reward?.id || route.reward?.itemId || 'Unknown specimen');
}
function routeTrade(alternative) {
 const label=alternative.label.charAt(0).toLowerCase()+alternative.label.slice(1);
 const terms=values=>allResources.filter(k=>values[k]).map(k=>`${values[k]} ${labels[k].toLowerCase()}`).join(' + ')||'no supplies';
 const consequence=alternative.disabled
   ? `${terms(alternative.cost)} → up to ${terms(alternative.reward)}. ${alternative.reason}`
   : `${allResources.filter(k=>alternative.immediate.deltas[k]||alternative.reward[k]).map(k=>`${signed(alternative.immediate.deltas[k])} ${labels[k].toLowerCase()}`).join(', ')} now.`;
 return `<span class="route-service ${alternative.disabled?'trade-unavailable':''}" data-route-trade="${esc(alternative.id)}">Or ${esc(label)}: ${esc(consequence)}</span>`;
}
export function routePanel(state,ui) {
 const departure=finalDepartureOffer(state,ui);
 const selected=selectedRouteForecast(state,ui,departure),direct=Boolean(selected?.finalDeparture);
 const harvesters=new Set(state.grid.filter(x=>x?.id==='radiovore').map(x=>x.uid));
 const decisive=selected?[...selected.events.filter(e=>harvesters.has(e.source)&&e.type==='organism'),...selected.events.filter(e=>['pressure','danger','dormant','mutation'].includes(e.type)),...selected.events.filter(e=>e.type==='hazard')].slice(0,3):[];
 const cards=getRoutes(state).map(r=>{
  const rescue=rescueOffer(state,r),offer=rescue?null:offerForRoute(state,r),open=ui.routePreview===r.id;
  const reward=rescue?'6 people seeking passage':`${rewardName(r)} · ${offer?.role||'supplies'}`;
  const price=rescue?rescue.text:`Acquire for ${offer?.cost||'unknown terms'}${offer?.disabled?` · ${offer.reason}`:''}`;
  return `<div class="route-card ${rescue?'rescue-route':''} ${open?'previewing':''}"><button class="route-option ${r.kind}" type="button" data-action="route" data-route="${r.id}" data-kind="${r.kind}" data-focus="route-${r.id}" aria-pressed="${open}"><span class="route-symbol">${icon(rescue?'crew':r.kind==='garden'?'biomass':r.kind==='salvage'?'power':'star')}</span><span class="route-copy"><span class="eyebrow">${rescue?'OPTIONAL RESCUE':typeNames[r.kind]}</span><strong>${esc(r.name)}</strong><span class="route-reward">${esc(reward)}</span><span class="route-price ${offer?.disabled?'danger-text':''}">${esc(price)}</span>${(offer?.alternatives||[]).map(routeTrade).join('')}<span class="route-risk">${icon(r.hazard)}${esc(hazardText(r))}</span></span>${icon('arrow','route-arrow')}</button>${open&&selected?`<div class="route-preview"><span class="section-label">${direct?'AFTER REFUSING THE SPECIMEN AND JUMPING':rescue?'IF YOU CONNECT SIX PEOPLE':'THIS SHIP AFTER THE JUMP'}</span><div class="route-projection">${allResources.map(k=>`<span class="${k}"><span class="route-stat-name">${labels[k]}</span>${icon(k)}<b data-route-projected="${k}">${selected.resources[k]}</b><small>${signed(selected.deltas[k])}</small><span class="sr-only"> ${labels[k]}</span></span>`).join('')}</div>${rescueForecastNote(selected)}${decisive.map(e=>`<p class="route-cause">${esc(e.text)}</p>`).join('')}<p class="certainty-note">${direct?'Includes the actual refusal and this crossing. No refits or changes to operation settings.':`${rescue?'Current layout, with the extra people aboard. Docking is optional at contact.':'Known crossing with your current layout; excludes contact trades.'} No hidden success roll; refit after contact.`}</p>${direct?finalDepartureControls(ui,departure):''}${button('take-route',`${direct?'Contact and refit':'Contact this signal'} ${icon('arrow')}`,`class="${direct?'secondary':'primary'}" data-route="${r.id}" data-focus="take-route"`)}${!direct?finalDepartureControls(ui,departure):''}</div>`:''}</div>`;
 }).join('');
 return `<span class="eyebrow mint">01 / CHOOSE A ROUTE</span><h2>Follow a signal.</h2><p>${state.ruleset===5?'Find life support for the people aboard, or carry more people when your ark can sustain them.':'Choose a find your ship needs, at a hazard it can withstand.'} Tap a signal to compare the crossing.</p>${crossingNotice(state)}<div class="route-list">${cards}</div>${Number.isInteger(ui.selected)&&state.grid[ui.selected]?`<div class="route-inspector">${inspector(state,ui,selected)}</div>`:''}<div class="quiet-tip">${icon('info')} Services at systems 4 and 7. At 7, you may evacuate with one retained strain.</div>`;
}

export function encounterPanel(state) {
  if(rescueOffer(state,state.route))return rescueEncounter(state);
  const e=getEncounter(state);
  if(!e) return '<h2>No signal</h2>';
  let reward=e.choices.find(c=>c.reward?.items?.length)?.reward.items[0] || state.route?.reward;
  reward=typeof reward==='string'?reward:reward?.item||reward?.id||reward?.itemId;
  return `<span class="eyebrow mint">02 / CONTACT</span><div class="encounter-art ${state.route?.kind}">${roomArt({id:CATALOG[reward]?reward:'echo-polyp'},{alt:CATALOG[reward]?.name||'An alien specimen'})}<span class="specimen-index">SPECIMEN / ${String(state.system).padStart(2,'0')}</span></div><h2>${esc(e.title)}</h2><p>${esc(e.text)}</p>${CATALOG[reward]?`<section class="specimen-scan" aria-label="Specimen scan"><span class="section-label">SCAN · ${esc(nameOf(reward))} · PER JUMP</span>${flows({id:reward,mutation:null},state)}<p>${esc(CATALOG[reward].description)}</p><p class="scan-risk">${esc(CATALOG[reward].risk)}</p><small>One open bay. Supplies are pooled. Placement stays reversible until you commit.</small></section>`:''}<div class="choice-list">${e.choices.map(c=>`<button class="choice-option" type="button" data-action="choice" data-choice="${c.id}" data-focus="choice-${c.id}" ${c.disabled?'disabled':''}><strong>${esc(c.label)} ${icon('arrow')}</strong><span>${esc(c.description)}</span><div class="choice-numbers">${Object.entries(c.cost||{}).filter(([,n])=>n).map(([r,n])=>`<span class="${r}">${icon(r)}−${n} ${labels[r].toLowerCase()}</span>`).join('')}${Object.entries(c.reward?.resources||{}).filter(([,n])=>n).map(([r,n])=>`<span class="${r}">${icon(r)}${signed(n)} ${labels[r].toLowerCase()}</span>`).join('')}${(c.reward?.items||[]).map(id=>`<span>+ ${esc(nameOf(id))}</span>`).join('')}</div>${c.disabled?`<span class="disabled-reason">${esc(c.disabledReason)}</span>`:''}</button>`).join('')}</div><div class="quiet-tip">${icon('info')} Trades happen now. Ship effects happen after your jump.</div>`;
}

function mutationDetail(specimen,branch,route,state=null,compact=false) {
 const index=state?.grid.findIndex(x=>x?.uid===specimen.uid)??-1;
 const candidate=state?.phase==='build'&&index>=0&&!specimen.mutation?act(state,{type:'MUTATE',index,branch}):state;
 const prediction=candidate&&index>=0?simulate(candidate,route):null;
 const symbioticActive=index>=0&&neighbours(index).some(i=>prediction?.grid[i]?.active&&prediction.grid[i]?.id!==specimen.id&&CATALOG[prediction.grid[i]?.id]?.kind==='organism');
 const comparison=mutationComparison(specimen,branch,route,{symbioticActive,ruleset:state?.ruleset});
 const cell=prediction?.cellReports?.[index];
 if(compact)return `<span class="mutation-choice-body">${roomArt({...specimen,mutation:branch},{alt:`${branch} ${nameOf(specimen.id)}`})}<span class="mutation-choice-copy"><strong>${esc(MUTATIONS.find(m=>m.id===branch)?.name||branch)}${branch==='symbiotic'?(symbioticActive?' · paired':' · isolated'):''}</strong><span>Base → strain: ${esc(comparison.text)}</span>${cell?.status==='dormant'?`<small class="danger-text">${esc(cell.reason)}</small>`:''}${comparison.paired?`<small>${symbioticActive?'Alone: '+esc(comparison.isolated):'Paired: '+esc(comparison.paired)}</small>`:''}<small>${branch==='feral'?(comparison.text==='No rate change in these conditions.'?'No operating benefit in this voyage.':'Greater yield; watch the added heat or food cost.'):branch==='efficient'?'Lower input; smaller main yield.':'Needs a different active species beside it.'}</small></span></span>`;
 return `<span class="mutation-comparison ${branch}"><span class="evolution-pair" aria-label="Mutation changes the organism">${roomArt({...specimen,mutation:null},{alt:`Base ${nameOf(specimen.id)}`})}<span aria-hidden="true">→</span>${roomArt({...specimen,mutation:branch},{alt:`${branch} ${nameOf(specimen.id)}`})}</span><b>Base → ${esc(branch)}${branch==='symbiotic'?(symbioticActive?' · paired here':' · isolated here'):''}${route?.hazard==='solar'?' · solar crossing':''}</b><span>${esc(comparison.text)}</span>${cell?.status==='dormant'?`<span class="danger-text">Next jump: ${esc(cell.reason)}</span>`:''}${comparison.paired?`<small>${symbioticActive?'Without an active neighbour: '+esc(comparison.isolated):'With a different active neighbour: '+esc(comparison.paired)}</small>`:''}<small>Per jump, when supplied. ${branch==='feral'?(specimen.id==='frost-lichen'?(state?.ruleset===5?'Stronger cooling consumes more food.':'No operating benefit in this voyage.'):'Extra heat is dangerous above 15.'):branch==='efficient'?'Lower demand, smaller yield.':'Neighbours must share an edge.'}</small></span>`;
}

function mutationReport(state,event) {
 const specimen=[...state.grid,...state.cargo].find(x=>x?.uid===event.source);
 if(!specimen?.mutation)return `<p>${esc(event.text)}</p>`;
 const cell=state.lastSimulation?.cellReports?.find(x=>x?.uid===event.source);
 const changedAfter=cell?.trajectory?.mutation?.before!==cell?.trajectory?.mutation?.after;
 const index=state.grid.findIndex(x=>x?.uid===specimen.uid);
 const symbioticActive=index>=0&&neighbours(index).some(i=>state.grid[i]?.active&&state.grid[i]?.id!==specimen.id&&CATALOG[state.grid[i]?.id]?.kind==='organism');
 const comparison=mutationComparison(specimen,specimen.mutation,state.route,{symbioticActive,ruleset:state.ruleset});
 const timing=changedAfter?'Changed after the crossing. The new rates start next jump.':cell?.status==='active'?'The new rates applied on this jump.':cell?'Dormant on this jump: no production.':'Stored in cargo: no production until grafted.';
 const actual=cell?.status==='active'&&!changedAfter?`This jump: ${rateText({input:cell.inputs,output:cell.outputs,defence:cell.defence})}${specimen.mutation==='symbiotic'?(symbioticActive?' · paired':' · isolated'):''}.`:'';
 return `<article class="mutation-highlight"><span class="evolution-pair">${roomArt({...specimen,mutation:null},{alt:`Base ${nameOf(specimen.id)}`})}<span aria-hidden="true">→</span>${roomArt(specimen,{alt:`${specimen.mutation} ${nameOf(specimen.id)}`})}</span><strong>${esc(nameOf(specimen.id))} is now ${esc(specimen.mutation)}.</strong>${actual?`<p class="mutation-actual">${esc(actual)}</p>`:''}<p>${changedAfter?'Next jump, if supplied: ':specimen.mutation==='symbiotic'?(symbioticActive?'With its active neighbour: ':'In isolation: '):''}${esc(comparison.text)}</p>${comparison.paired?`<small>${symbioticActive?'Without an active neighbour: '+esc(comparison.isolated):'With a different active neighbour: '+esc(comparison.paired)}</small>`:''}<small>${timing} ${state.route?.hazard==='solar'?'Numbers shown for solar radiation.':''}</small></article>`;
}

function inspector(state,ui,forecast) {
 const specimen=ui.placing?state.cargo.find(x=>x.uid===ui.placing):Number.isInteger(ui.selected)?state.grid[ui.selected]:null;
 if(!specimen)return `<div class="empty-inspector"><span class="eyebrow">MAKE ROOM FOR LIFE</span><h3>Your ship is changing.</h3><p>Tap a room to inspect it, or choose a specimen in cargo. Your plan stays reversible until the jump.</p></div>`;
 const data=CATALOG[specimen.id],onShip=Number.isInteger(ui.selected)&&state.grid[ui.selected]?.uid===specimen.uid;
 const cell=onShip?forecast?.cellReports?.[ui.selected]:null;
 const trajectory=cell?.trajectory,targets=cell?.localTargets||[];
 const activeRoute=state.route||getRoutes(state).find(r=>r.id===ui.routePreview);
 const jumpDemand=['engine','crew'].includes(specimen.id)?forecast?.events?.find(e=>e.type==='demand'&&e.source==='jump')?.text:null;
 const age=trajectory?.age,exposure=trajectory?.solarExposures,mutation=trajectory?.mutation;
 const isSeed=state.seedUids?.includes(specimen.uid);
 return `<div class="inspector"><div class="specimen-heading">${roomArt(specimen)}<div><span class="eyebrow ${data.kind==='organism'?'mint':''}">${isSeed?'INHERITED SEED':specimen.mutation?`${specimen.mutation} MUTATION`:data.kind==='organism'?'ALIEN ORGANISM':'SHIP MODULE'}</span><h3>${esc(data.name)}</h3></div></div>${cell?`<p class="operating-status ${cell.status==='dormant'?'danger-text':'mint'}">${icon(cell.status==='dormant'?'alert':'check')}<span>${esc(cell.reason==='Operated this jump.'?'Runs on the next jump.':cell.reason||`${cell.status} next jump`)}</span></p>`:''}${starvationTiming(cell,forecast)}${flows(specimen,state,forecast)}<p class="timing-note">${jumpDemand?esc(jumpDemand)+' ':''}Per committed jump. Supplies are pooled across the ship.</p>${isSeed?'<p class="seed-cost">Growing this inherited seed costs 3 food and an open bay on commit.</p>':''}${targets.map(t=>`<p class="synergy-note ${['danger','mutation'].includes(t.kind)?'danger-text':''}" data-target-cell="${t.index}">${icon(['danger','mutation'].includes(t.kind)?'alert':'biomass')}Bay ${t.index+1}: ${esc(t.text)}</p>`).join('')}${age||exposure?`<div class="trajectory">${age?`<span>Active jumps ${age.before} → ${age.after}</span>`:''}${specimen.id==='radiovore'&&exposure?`<span>Solar exposure ${exposure.before} → ${exposure.after}; next mutation in ${2-exposure.after%2} solar ${2-exposure.after%2===1?'jump':'jumps'}</span>`:''}${specimen.id==='grave-moss'&&age?`<span>Growth every 3 active jumps; an open neighbouring bay is required.</span>`:''}${mutation&&mutation.before!==mutation.after?`<span>After this jump: ${esc(mutation.before||'base')} → ${esc(mutation.after||'base')}.</span>`:''}</div>`:''}<details class="specimen-details" ${ui.specimenDetailsOpen?'open':''}><summary>${specimen.mutation?'Biology & mutation details':'How this room works'} ${icon('plus')}</summary>${specimen.mutation?mutationDetail(specimen,specimen.mutation,activeRoute,state):`<p class="specimen-description">${esc(data.description)}</p><p class="risk-line">${icon('info')}${esc(data.risk||'Needs a stable supply to stay active.')}</p>`}${data.anchored?`<p class="anchored">${icon('lock')} Anchored core room</p>`:''}</details>${onShip&&state.phase==='build'&&data.kind==='organism'&&!specimen.mutation?`<details class="mutation-options" ${ui.mutationOpen?'open':''}><summary>${icon('mutation')} Plan mutation <span>3 food</span></summary><div>${MUTATIONS.map(m=>`<button type="button" data-action="mutate" data-branch="${m.id}" aria-label="Plan ${esc(m.name)} ${esc(data.name)} for 3 food">${mutationDetail(specimen,m.id,activeRoute,state,true)}</button>`).join('')}<p class="mutation-draft-note">3 food on commit. Compare freely; Undo until the jump.</p></div></details>`:''}${ui.placing?`<div class="cargo-reject">${button('discard','Plan discard','class="text-button danger-text" data-focus="discard"')}<span>No refund · Undo until commit</span></div>`:''}</div>`;
}

export function cargo(state,ui) {
 return `<div class="cargo"><div class="section-label"><span>CARGO <b>${state.cargo.length}/8</b></span><span>Tap to plan a graft</span></div><div class="cargo-tray">${state.cargo.length?state.cargo.map(item=>`<button type="button" class="cargo-item ${ui.placing===item.uid?'selected':''}" data-action="cargo" data-uid="${item.uid}" data-item="${item.id}" data-focus="cargo-${item.uid}" aria-label="Graft ${esc(nameOf(item.id))}${item.mutation?', '+item.mutation:''}" draggable="true">${roomArt(item)}<span>${esc(nameOf(item.id))}</span>${item.mutation?icon('mutation','cargo-mutation'):''}</button>`).join(''):'<p class="cargo-empty">An empty hold. Find new life on your next route.</p>'}</div></div>`;
}
export function forecastPanel(state,forecast,ui) {
  const warning=forecast.committable===false?getPlan(state).disabledReason:forecast.outcome==='loss'?'This jump will end the voyage.':forecast.events.find(e=>['pressure','danger','warning','dormant','damage','starvation'].includes(e.type))?.text;
  return `<section class="forecast" tabindex="-1" aria-label="Jump forecast"><div class="section-label"><span>AFTER JUMP</span><span>${forecast.committable===false?'PROVISIONAL · PLAN INVALID':forecast.outcome==='loss'?'NON-VIABLE':'PROJECTED STORES'}</span></div><div class="forecast-values">${allResources.map(r=>`<div class="${r}"><span>${icon(r)}${labels[r]}</span><b data-projected="${r}">${forecast.resources[r]}</b><small class="${(r==='heat'?forecast.deltas[r]>0:forecast.deltas[r]<0)?'negative':'positive'}" data-delta="${r}">${signed(forecast.deltas[r])}</small></div>`).join('')}</div><p class="forecast-summary ${warning?'warning':''}">${icon(warning?'alert':'check')}${esc(warning||'Life support is holding. Your ark can make this jump.')}</p>${forecast.events.some(e=>e.type==='dormant')?'<p class="operating-timing">These are end-of-jump stores. Rooms pay inputs earlier. Machines run before biology; one organism’s output cannot fund another until the next jump.</p>':''}<details class="causes" ${ui.causesOpen?'open':''}><summary>What changes and why ${icon('plus')}</summary><ol>${forecast.events.map(e=>`<li class="${e.type}">${esc(e.text)}</li>`).join('')}</ol></details></section>`;
}
function selectionContext(state,ui) {
 const item=ui.placing?state.cargo.find(x=>x.uid===ui.placing):state.grid[ui.selected];
 if(!item)return '';
 const onShip=!ui.placing&&Number.isInteger(ui.selected);
 return `<div class="selection-context"><span><small>${onShip?`BAY ${String(ui.selected+1).padStart(2,'0')}`:'CARGO · GRAFT PREVIEW'}</small><b>${esc(nameOf(item.id))}</b></span>${button(onShip?'show-room':'show-bays',onShip?'Show room':'Show holds','class="secondary"')}</div>`;
}

export function buildPanel(state,ui,forecast) {
 const plan=getPlan(state),service=[4,7].includes(state.system);
 const repairFull=state.resources.hull+plan.repairs*6>=30;
 const planLabel=state.plan?.pendingExchange?allResources.filter(k=>plan.costs[k]).map(k=>`${signed(-plan.costs[k])} ${labels[k].toLowerCase()}`).join(' · ')||'No supply change':`${plan.costs.biomass} food`;
 return `<span class="eyebrow mint">03 / PLAN YOUR SHIP</span><h2>${state.turn===0?'A little room to grow.':'What will it become?'}</h2>${selectionContext(state,ui)}${inspector(state,ui,forecast)}${cargo(state,ui)}${crossingNotice(state)}<div class="plan-summary"><div><span class="section-label">DRAFT SUPPLIES · ON COMMIT</span><strong data-plan-food="${plan.costs.biomass}">${esc(planLabel)}</strong><p>${plan.refitsUsed}/${plan.refitLimit} refits · ${plan.reclaimedBays.length} holds reclaimed${plan.uprootedUids.length?` · ${plan.uprootedUids.length} uprooted, dormant for this jump`:''}</p></div>${state.plan?.history.length?button('reset','Reset all changes','class="text-button" data-focus="reset"'):''}</div>${forecastPanel(state,forecast,ui)}${state.ruleset===5?`<p class="forecast-population" data-people-forecast="${Math.max(0,forecast.crew)}">${Math.max(0,forecast.crew)} people after this jump</p>`:''}${trendMarkup(state)}<div class="build-repair">${button('repair',`${icon('repair')} Plan repair`,`class="text-button" data-focus="repair" ${repairFull||plan.repairs+(state.repairsThisTurn||0)>=2?'disabled':''}`)}<span>${repairFull?'Hull is intact after planned repairs':plan.repairs+(state.repairsThisTurn||0)>=2?'Two repairs used this stop':'4 food → 6 hull on commit'}</span></div>${service?`<section class="service-stop"><span class="eyebrow">SERVICE BEACON</span>${portExchangeMarkup(state)}<p>Open a deeper refit at a food cost.</p>${button('buy-refits','+2 refits · 3 food',`class="secondary" ${plan.refitPurchases>=2?'disabled':''}`)}${state.system===7?button('evacuate','Evacuate · rescue one strain','class="text-button" data-focus="evacuate"'):''}</section>`:''}<div class="departure">${!plan.committable?`<p class="departure-warning">${icon('alert')}${esc(plan.disabledReason)}</p>`:forecast.outcome==='loss'?`<p class="departure-warning">${icon('alert')}This jump will end your voyage. Reconfigure to survive.</p>`:''}<div class="commit-controls">${state.plan?.history.length?button('undo',`${icon('back')}<span>Undo</span>`,'class="secondary commit-undo" data-focus="undo"'):''}<button type="button" class="primary ${forecast.outcome==='loss'?'danger':''}" data-action="depart" data-focus="depart" ${plan.committable?'':'disabled'}><span>Commit & jump to ${String(Math.min(10,state.system+1)).padStart(2,'0')}<small>${esc(planLabel)} on commit · ${plan.refitsUsed}/${plan.refitLimit} refits</small></span>${icon('arrow')}</button></div></div>`;
}

export function reportPanel(state,ui) {
  const report=state.lastReport;
  const before=report?.before||{};
  const mutations=(report?.events||[]).filter(e=>e.type==='mutation');
  const summary=reportSummary(state);
  const repair=plannedRepairEvent(report);
  const highlights=[...(report?.events||[]).filter(e=>['pressure','danger','dormant'].includes(e.type)),...(repair?[repair]:[]),...(report?.events||[]).filter(e=>e.type==='growth'),...(report?.events||[]).filter(e=>e.type==='hazard'),...(report?.events||[]).filter(e=>e.type==='synergy')].slice(0,4);
  return `<span class="eyebrow mint">04 / JUMP COMPLETE</span><div class="arrival-mark ${['loss','warning'].includes(summary.tone)?'loss':''}">${icon(['loss','warning'].includes(summary.tone)?'alert':'star')}</div><h2>${summary.title}</h2><p>${esc(summary.text)}</p><div class="report-resources">${allResources.map(r=>`<div class="${r}"><span>${icon(r)}${labels[r]}</span><strong>${before[r]??state.resources[r]-(report?.deltas?.[r]||0)} <span>→</span> <b data-actual="${r}">${state.resources[r]}</b></strong><small>${signed(report?.deltas?.[r]||0)}</small></div>`).join('')}</div><div class="report-highlights">${highlights.filter(e=>['pressure','danger','dormant'].includes(e.type)).map(e=>`<p>${icon('alert')}${esc(e.text)}</p>`).join('')}${mutations.map(e=>mutationReport(state,e)).join('')}${highlights.filter(e=>!['pressure','danger','dormant'].includes(e.type)).map(e=>`<p>${icon(e.delta?.hull<0?'alert':'check')}${esc(e.text)}</p>`).join('')}</div><details class="causes"><summary>Full ship log ${icon('plus')}</summary><ol>${(report?.events||[]).map(e=>`<li>${esc(e.text)}</li>`).join('')}</ol></details>${button('continue',`Choose next route ${icon('arrow')}`,'class="primary" data-focus="continue"')}`;
}
export function endPanel(state,ui) {
 const win=state.outcome==='win',evacuated=state.outcome==='evacuation',score=scoreRun(state),pending=state.banking?.status==='pending';
 const tradeLoss=!win&&!evacuated&&state.encounterId&&state.encounterId!==state.lastReport?.encounterId;
 const people=getPeopleRecord(state),capacity=state.ruleset===5;
 return `<span class="eyebrow ${win||evacuated?'mint':'danger-text'}">${win?'EOS REFUGE / ARRIVAL':evacuated?'SERVICE BEACON / EVACUATION':'TRANSMISSION LOST / GAME OVER'}</span><div class="arrival-mark ${win||evacuated?'':'loss'}" aria-hidden="true">${icon(win||evacuated?'biomass':'alert')}</div><h2>${win?'A new world.<br>A new kind of life.':evacuated?'The ship ends.<br>Your lineage lives.':'Your ark<br>has fallen silent.'}</h2><p>${esc(win?(capacity?'Your ark reached Eos Refuge. Its living cargo and arrival blueprint are preserved.':'The ark reached Eos Refuge with surviving crew. Its arrival blueprint is saved.'):evacuated?'The people aboard reached the beacon. The ark is abandoned; uncommitted refits were discarded.':tradeLoss?'The encounter cost exhausted the hull before departure.':state.crew<=0?'Life support failed. The crew could not survive the crossing.':'Your hull failed under the strain. The ship could not survive the crossing.')}</p>${peopleEnding(state)}<div class="ending-build"><span>${win?'ARRIVAL RECORD':evacuated?'EVACUATION RECORD':'FINAL TRANSMISSION'}</span>${esc(classifyBuild(state).name)}<b>${score.total}<small> VIABILITY SCORE</small></b></div><div class="end-stats">${capacity?`<span><b>${people.embarked}</b> people embarked</span>`:`<span><b>${Math.max(0,state.crew)}/6</b> ${win||evacuated?'crew survived':'crew at last contact'}</span>`}<span><b>${state.turn}</b> jumps crossed</span></div>${!win&&!evacuated?`<div class="failure-reasons">${tradeLoss?'<p>The hull reached zero during the encounter. No jump was made.</p>':(state.lastReport?.events||[]).filter(e=>['pressure','damage','danger','starvation','warning'].includes(e.type)).slice(-3).map(e=>`<p>${esc(e.text)}</p>`).join('')}</div>`:''}${!win&&!evacuated?'<p class="loss-legacy">The ship is lost. Your observations and previously banked genomes remain. Unbanked strains did not survive.</p>':''}${win||evacuated?bankingPanel(state,ui):''}${pending?'':button('new',`Begin successor voyage ${icon('arrow')}`,'class="primary" data-focus="new"')}${button('archive','Explore the lineage','class="secondary full" data-focus="end-archive"')}`;
}

export function archivePage(state,ui,snapshot) {
 const archive=snapshot.archive, found=new Set([...(archive.discoveries||[]),...(archive.genomes||[]).map(g=>g.id)]);
 return `<main class="archive-page" id="decision" tabindex="-1"><div class="archive-heading"><div><span class="eyebrow mint">A MEMORY OF ALL THAT LIVED</span><h1>Genome Archive<span>.</span></h1><p>Observations remember what lived. Banked genomes can seed the next voyage.</p></div>${button('back',`${icon('back')} Back to ship`,'class="secondary" data-focus="back"')}</div><div class="archive-stats"><div><strong>${found.size}</strong><span>discoveries</span></div><div><strong>${(archive.mutations||[]).length}</strong><span>mutations</span></div><div><strong>${(archive.synergies||[]).length}</strong><span>synergies</span></div><div><strong>${(archive.completedRuns||[]).length}</strong><span>voyages ended</span></div></div>${genomeBank(archive)}${blueprintGallery(archive)}<h2 class="observations-title">Observed life</h2><div class="archive-specimens">${ORGANISMS.map(value=>{const item=typeof value==='string'?CATALOG[value]:value;const known=found.has(item.id);return `<article class="archive-specimen ${known?'discovered':'undiscovered'}">${roomArt(item,{alt:known?item.name:'Undiscovered organism'})}<div><span class="eyebrow">${known?'OBSERVED':'UNSEQUENCED'}</span><h2>${known?esc(item.name):'Unknown life'}</h2><p>${known?esc(item.description):'Follow a distant signal to find this organism.'}</p>${known?flows({id:item.id,mutation:null}):''}</div></article>`;}).join('')}</div><div class="archive-records"><section><h2>Mutations</h2>${(archive.mutations||[]).length?`<ul>${archive.mutations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Alter a living specimen to discover a new branch.</p>'}</section><section><h2>Synergies</h2>${(archive.synergies||[]).length?`<ul>${archive.synergies.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Place compatible organisms side by side.</p>'}</section><section><h2>Endings</h2>${Object.entries(archive.endings||{}).map(([k,n])=>`<p>${esc(k)} <b>×${n}</b></p>`).join('')||'<p>Your first voyage is still being written.</p>'}<p>Best score <b>${archive.bestScore||0}</b></p></section></div></main>`;
}
